name       : radiotray-ng
version    : 0.2.6
release    : 18
source     :
    - https://github.com/ebruck/radiotray-ng/archive/v0.2.6.tar.gz : 05e1b9ac7342b276fff6395a38719264f9bc47b28aadd4938c5bbe3303c67553
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : An Internet radio player for Linux
description: |
    An Internet radio player for Linux
builddeps  :
    - pkgconfig(appindicator-0.1)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(jsoncpp)
    - pkgconfig(libbsd)
    - pkgconfig(libcurl)
    - pkgconfig(libnotify)
    - pkgconfig(libxdg-basedir)
    - pkgconfig(ncursesw)
    - libboost-devel
    - lsb-release
    - wxwidgets-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
