name       : radiotray-ng
version    : 0.2.0
release    : 4
source     :
    - https://github.com/ebruck/radiotray-ng/archive/v0.2.0.tar.gz : 1965e5dc0853349c3141ac843f640587fb1e0edf50a44be23da783adfe98a0d5
license    : GPL-3.0
component  : multimedia.audio
summary    : An Internet radio player for Linux
description: |
    An Internet radio player for Linux
builddeps  :
    - pkgconfig(appindicator-0.1)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(jsoncpp)
    - pkgconfig(libbsd)
    - pkgconfig(libcurl)
    - pkgconfig(libnotify)
    - pkgconfig(libxdg-basedir)
    - pkgconfig(ncursesw)
    - libboost-devel
    - lsb-release
    - wxwidgets-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
