name       : radiotray-ng
version    : 0.2.2
release    : 11
source     :
    - https://github.com/ebruck/radiotray-ng/archive/v0.2.2.tar.gz : 85de0228b7927add4c143a5bb757ab026041921d640dc0b9b0cdfef519470d88
license    : GPL-3.0-only
component  : multimedia.audio
summary    : An Internet radio player for Linux
description: |
    An Internet radio player for Linux
builddeps  :
    - pkgconfig(appindicator-0.1)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(jsoncpp)
    - pkgconfig(libbsd)
    - pkgconfig(libcurl)
    - pkgconfig(libnotify)
    - pkgconfig(libxdg-basedir)
    - pkgconfig(ncursesw)
    - libboost-devel
    - lsb-release
    - wxwidgets-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
