name       : radiotray-ng
version    : 0.2.5
release    : 15
source     :
    - https://github.com/ebruck/radiotray-ng/archive/v0.2.5.tar.gz : 9b34f13f4290c98be9be555873d05507bbe7bcaa4ad0924655a4f38c8d55fe64
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : An Internet radio player for Linux
description: |
    An Internet radio player for Linux
builddeps  :
    - pkgconfig(appindicator-0.1)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(jsoncpp)
    - pkgconfig(libbsd)
    - pkgconfig(libcurl)
    - pkgconfig(libnotify)
    - pkgconfig(libxdg-basedir)
    - pkgconfig(ncursesw)
    - libboost-devel
    - lsb-release
    - wxwidgets-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
