name       : radiotray-ng
version    : 0.2.3
release    : 13
source     :
    - https://github.com/ebruck/radiotray-ng/archive/v0.2.3.tar.gz : a8dacc297ea1d547aadadf54ed081555aacecbed4d8b1b903188bead0c3d6fcb
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : An Internet radio player for Linux
description: |
    An Internet radio player for Linux
builddeps  :
    - pkgconfig(appindicator-0.1)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(jsoncpp)
    - pkgconfig(libbsd)
    - pkgconfig(libcurl)
    - pkgconfig(libnotify)
    - pkgconfig(libxdg-basedir)
    - pkgconfig(ncursesw)
    - libboost-devel
    - lsb-release
    - wxwidgets-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Mark-header-includes-as-system.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
