name       : radiotray-ng
version    : 0.2.7
release    : 19
source     :
    - https://github.com/ebruck/radiotray-ng/archive/v0.2.7.tar.gz : 0ee5459ea49cc78e4cdf2399061c0caf352d8a963c67a7e99c6cc81bb47288d3
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : An Internet radio player for Linux
description: |
    An Internet radio player for Linux
builddeps  :
    - pkgconfig(appindicator-0.1)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(jsoncpp)
    - pkgconfig(libbsd)
    - pkgconfig(libcurl)
    - pkgconfig(libnotify)
    - pkgconfig(libxdg-basedir)
    - pkgconfig(ncursesw)
    - libboost-devel
    - lsb-release
    - wxwidgets-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
