name       : radiotray-ng
version    : 0.1.5
release    : 1
source     :
    - https://github.com/ebruck/radiotray-ng/archive/v0.1.5.tar.gz : 8610c18d1cfad3510d7377a7d963486bf9b82c469f6184231f61d04e46eaae46
license    : GPL-3.0
component  : multimedia.audio
summary    : An Internet radio player for Linux
description: |
    An Internet radio player for Linux
builddeps  :
    - pkgconfig(appindicator-0.1)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(jsoncpp)
    - pkgconfig(libbsd)
    - pkgconfig(libcurl)
    - pkgconfig(libnotify)
    - pkgconfig(libxdg-basedir)
    - pkgconfig(ncursesw)
    - libboost-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
