name       : radiotray-ng
version    : 0.2.4
release    : 14
source     :
    - https://github.com/ebruck/radiotray-ng/archive/v0.2.4.tar.gz : 404dae294bbb9927aadf789cea00b33baedf784658187a21a83433a1efe18a3a
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : An Internet radio player for Linux
description: |
    An Internet radio player for Linux
builddeps  :
    - pkgconfig(appindicator-0.1)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(jsoncpp)
    - pkgconfig(libbsd)
    - pkgconfig(libcurl)
    - pkgconfig(libnotify)
    - pkgconfig(libxdg-basedir)
    - pkgconfig(ncursesw)
    - libboost-devel
    - lsb-release
    - wxwidgets-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
