name       : radiotray-ng
version    : 0.2.1
release    : 5
source     :
    - https://github.com/ebruck/radiotray-ng/archive/v0.2.1.tar.gz : 63cdbcd18172ffc9c75cc6cb89ec720bb44492e2b4c87869cfc4232fc981eac5
license    : GPL-3.0
component  : multimedia.audio
summary    : An Internet radio player for Linux
description: |
    An Internet radio player for Linux
builddeps  :
    - pkgconfig(appindicator-0.1)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(jsoncpp)
    - pkgconfig(libbsd)
    - pkgconfig(libcurl)
    - pkgconfig(libnotify)
    - pkgconfig(libxdg-basedir)
    - pkgconfig(ncursesw)
    - libboost-devel
    - lsb-release
    - wxwidgets-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
